### ISSUE TITLE
Add a GUI

### ISSUE THREAD

**Issue by vivekpatel42** [UCSB-CS56-Projects/cs56-utilities-GoldScheduler#1]
As of now, the GUI launches as a blank white page with no login screen or anything. Add a functional GUI for the user to interact with the backend service. Most of the GUI elements seem to be coded in, but on both Mac OS X and CSIL, the GUI does not work.

**Comment by vivekpatel42** [comment]
F16 OK (350 pts)

**Comment by pconrad** [comment]
So, it turns out that the GUI wasn't working because of a problem with the database connection.

@milanes1 and @jamesy36 met with @ncbrown1 and worked on getting that to work.  I also met with them today.    Between the four of us, we got this migrated over to sqlite3 with the build.xml and the jar files update.    Nick and I did most of the work, but James and Arturo should definitely get some credit for having brought the issue to us working through it with us.   

Check with me if there are any questions.  I want to be sure they don't get credit for work they didn't do, but at the same time, I also don't want them to get cheated out of points they have legitimately earned, and this is a case of a judgement call in between the two extremes of 0 points and all the points.
